// PAGINATION
const DEFAULT_PAGE_SIZE = 20;

// FETCH STATES
const FETCH_PENDING = "FETCH_PENDING";
const FETCH_COMPLETE = "FETCH_COMPLETE";
const FETCH_ERROR = "FETCH_ERROR";


module.exports = {
  DEFAULT_PAGE_SIZE,
  FETCH_PENDING,
  FETCH_COMPLETE,
  FETCH_ERROR,
}
