import React, { useEffect, useState } from "react";
import Paper from "@material-ui/core/Paper";
import makeStyles from "@material-ui/core/styles/makeStyles";
import IconButton from "@material-ui/core/IconButton";
import Table from "@material-ui/core/Table";
import TableBody from "@material-ui/core/TableBody";
import TableCell from "@material-ui/core/TableCell";
import TableContainer from "@material-ui/core/TableContainer";
import TableHead from "@material-ui/core/TableHead";
import TableRow from "@material-ui/core/TableRow";
import Tooltip from "@material-ui/core/Tooltip";
import HighlightOffIcon from "@material-ui/icons/HighlightOff";
import EditIcon from "@material-ui/icons/Edit";
import { useDispatch, useSelector } from "react-redux";
import { adminOrderStatusThunk, fetchAdminOrders } from "../store/adminInfo";
import ProductFormStyling from "./AdminProductFormDialog";
import { useHistory, useLocation } from "react-router-dom";
import { getQueryParam, setQueryParam } from "../utility-funcs/query";
import Pagination from "./ListPagination";
import Grid from "@material-ui/core/Grid";
import Button from "@material-ui/core/Button";
